# -*- coding: utf-8 -*-
"""Appendicitis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18rl3YcgMHvFkJwjwB8ZpFK_-pX5q6zyn

# Importing Appendicitis Dataset
"""

!wget "https://github.com/frontiertechinstitute/datasets/releases/download/appendicitis-US-dataset-v1/app_data_clean.csv"

!wget "https://github.com/frontiertechinstitute/datasets/releases/download/appendicitis-US-dataset-v1/Data.Summary.xlsx"

!wget "https://github.com/frontiertechinstitute/datasets/releases/download/appendicitis-US-dataset-v1/US_Pictures.zip"

!unzip US_Pictures.zip

from PIL import Image

img = Image.open("US_Pictures/861.2 App_M.bmp")

img

#from google.colab import drive
#drive.mount('/content/drive')

"""# Appendicitis EDA

"""

import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

patient_df = pd.read_csv('app_data_clean.csv') # Imports the dataset

patient_df.info() # Calls the first 10 rows

import os
import re

"""# Req Columns

"""

image_dir = "US_Pictures"
metadata_file = "app_data_clean.csv"


required_columns = [
   'WBC_Count','Hemoglobin','Neutrophil_Percentage','CRP','Thrombocyte_Count','Paedriatic_Appendicitis_Score'
    # Add more features here you would use
]

pattern = r"^(\d+)\.(\d+)\s*(.*?)\.bmp$"

os.listdir("US_Pictures")

os.path.join("US_Pictures", "train", "1.2 Ileitis.png")

image_records = []
for filename in os.listdir(image_dir):

    # Only process bmp files
    if not filename.lower().endswith(".bmp"):
        continue

    filepath = os.path.join(image_dir, filename)

    # Expected format:
    # {pid}.{im_number} {description}.bmp
    #
    # Example:
    # 123.4 Abdomen transverse.bmp

    match = re.match(
        r"^(\d+)\.(\d+)\s*(.*?)\.bmp$",
        filename,
        flags=re.IGNORECASE
    )

    if match:
        pid = int(match.group(1))
        image_number = int(match.group(2))
        description = match.group(3).strip()

    else:
        # Handle unexpected filenames
        # Try to at least recover the patient ID
        fallback = re.match(r"^(\d+)", filename)

        if fallback:
            pid = int(fallback.group(1))
        else:
            pid = None

        image_number = None
        description = filename.replace(".bmp", "")

    image_records.append({
        "pid": pid,
        "image_number": image_number,
        "description": description,
        "filename": filename
    })

images_df = pd.DataFrame(image_records)

images_df.head()

len(images_df)

image_summary = (
        images_df
        .groupby("pid")
        .agg(
            num_images=("filename", "count"),
            image_numbers=("image_number", lambda x: sorted(
                [i for i in x.dropna().unique()]
            )),
            image_descriptions=("description", lambda x: sorted(
                list(set(x))
            ))
        )
        .reset_index()
    )

image_summary.head()

metadata = pd.read_csv(metadata_file)


# Convert US_Number from float to integer where possible
metadata["US_Number_clean"] = (
    pd.to_numeric(metadata["US_Number"], errors="coerce")
    .dropna()
    .astype(int)
)

"""
errors = 'coerce' tells pandas, "if you find a value that cannot be converted, replace it with missing
(NaN) instead of throwing an error"
"""

# Unique patients appearing in metadata
metadata_patients = (
    metadata["US_Number_clean"]
    .dropna()
    .unique()
)

patients_without_images = sorted(
    set(metadata_patients) -
    set(image_summary["pid"])
)

len(patients_without_images)

# All unique patients from either source
all_patients = pd.DataFrame({
    "pid": sorted(
        set(image_summary["pid"])
        .union(set(metadata_patients))
    )
})

final_df = (
    all_patients
    .merge(
        image_summary,
        on="pid",
        how="left"
    )
)


# Add image presence indicator
final_df["has_images"] = (
    final_df["num_images"]
    .fillna(0)
    .astype(int)
    .gt(0) # Greater than 0
)

final_df["num_images"] = (
    final_df["num_images"]
    .fillna(0)
    .astype(int)
)

# Does patient appear in metadata?
metadata_pid_set = set(metadata_patients)

final_df["appears_in_metadata"] = (
    final_df["pid"]
    .isin(metadata_pid_set)
)

# Add metadata completeness information

# Keep only the needed columns plus patient identifier
metadata_subset = metadata[["US_Number_clean"] + required_columns].copy()

metadata_subset = (
        metadata_subset
        .rename(columns={"US_Number_clean": "pid"})
        .drop_duplicates("pid")
    )

final_df = final_df.merge(
        metadata_subset,
        on="pid",
        how="left"
    )

final_df["all_required_fields_present"] = (
        final_df[required_columns]
        .notna()
        .all(axis=1)
    )

final_df = final_df.sort_values("pid").reset_index(drop=True)
print(len(final_df)) # number of patients we have either in metadata or in images folder
final_df.head(100)

"""# Copy of final_df

"""

copyfinal_df = final_df

copyfinal_df = final_df.drop(axis = 0, columns = ['WBC_Count','has_images','appears_in_metadata',
                                                  'Hemoglobin','Neutrophil_Percentage','CRP','Thrombocyte_Count',
                                                  'all_required_fields_present','has_images'])

copyfinal_df

copyfinal_df = copyfinal_df.dropna()

copyfinal_df.info()

"""# Setting Up Data Loaders"""

from sklearn.model_selection import train_test_split

train_pids , test_pids = train_test_split(copyfinal_df['pid'], test_size = 0.2, shuffle = True  )

print(test_pids)

def split_finder(row):
  if row['pid'] in train_pids:
    return 'train'
  else:
    return 'test'

copyfinal_df.head()

copyfinal_df['pid'].isna().sum()

images_df.info()

copyfinal_df.info()

images_df.head()

copyfinal_df['datasplit'] = 'train'

copyfinal_df.loc[copyfinal_df['pid'].isin(test_pids), 'datasplit'] = 'test'

copyfinal_df['datasplit'].value_counts()

#image_df['label'] = copyfinal_df['pid'].isin(test_pids), 'datasplit' = 'test'

copyfinal_df['pid'] = copyfinal_df['pid'].astype(int)

copyfinal_df.head()

images_df = images_df.merge(copyfinal_df, on = 'pid', how = 'inner')

images_df.head()

images_df['label'] = images_df.apply(lambda row: int(row['Paedriatic_Appendicitis_Score'] >= 5), axis = 1 )

images_df['Paedriatic_Appendicitis_Score'].value_counts()

images_df.head()

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision.models import resnet18, ResNet18_Weights
from torchvision.datasets import ImageFolder
from torchvision import transforms
from torch.utils.data import DataLoader
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision

from torchvision import datasets
from torchvision import transforms
from torch.utils.data.sampler import SubsetRandomSampler
from torch.utils.data import Dataset

"""# Data Loaders

"""

for_dataloader = images_df[['pid','label','datasplit','filename']]

dataloader_traindf = for_dataloader[for_dataloader['datasplit'] == 'train']

dataloader_testdf = for_dataloader[for_dataloader['datasplit'] == 'test']

from torch.utils.data import Dataset
from PIL import Image

class ImageDataset(Dataset):

 def __init__(self, df, transform = None):
  self.df = df
  self.transform = transform

 def __len__(self):
  return len(self.df)

 def __getitem__(self, idx):

  row = self.df.iloc[idx]

  image = Image.open(f'US_Pictures/{row.filename}').convert('RGB')

  if self.transform is not None:

    image = self.transform(image)

  label = int(row.label)

  return image, label

train_dataset = ImageDataset(
    dataloader_traindf,
    transform =  transforms.Compose([
                                     transforms.Resize((580, 800)),
                                     transforms.ToTensor(),
                                     transforms.Normalize(mean=[0.485,0.456,0.406], std=[0.229,0.224,0.225]),

                                     ])
)

test_dataset = ImageDataset(
    dataloader_testdf,
    transform =  transforms.Compose([
                                     transforms.Resize((580, 800)),
                                     transforms.ToTensor(),
                                     transforms.Normalize(mean=[0.485,0.456,0.406], std=[0.229,0.224,0.225]),

                                     ])
)

train_loader = DataLoader(train_dataset, batch_size = 8, shuffle = True)

test_loader = DataLoader(test_dataset, batch_size = 8, shuffle = True)

my_transform = transforms.Compose([
                                     transforms.Resize((580, 800)),
                                     transforms.ToTensor(),
                                     transforms.Normalize(mean=[0.485,0.456,0.406], std=[0.229,0.224,0.225]),

                                     ])

final_df.info()

patient_df = patient_df[['Contralateral_Rebound_Tenderness', 'WBC_Count','Appendix_on_US','Sex','Age','Paedriatic_Appendicitis_Score','Alvarado_Score','US_Number']]

final_df

final_df = final_df.dropna()

final_df.info()

#final_df['Sex'] = final_df['Sex'].replace({'male': 1})
#final_df['Sex'] = final_df['Sex'].replace({'female': 0})
#final_df['Contralateral_Rebound_Tenderness'] = final_df['Contralateral_Rebound_Tenderness'].replace({'yes': 1})
#final_df['Contralateral_Rebound_Tenderness'] = final_df['Contralateral_Rebound_Tenderness'].replace({'no': 0})
#final_df['Appendix_on_US'] = final_df['Appendix_on_US'].replace({'yes': 1})
#final_df['Appendix_on_US'] = final_df['Appendix_on_US'].replace({'no': 0})
#final_df['Loss_of_Appetite'] = final_df['Loss_of_Appetite'].replace({'yes': 1})
#final_df['Loss_of_Appetite'] = final_df['Loss_of_Appetite'].replace({'no': 0})
final_df

"""
#  PCA Plot with Seaborn"""

#Importing libraries
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

from sklearn.datasets import make_classification
from sklearn.feature_selection import SelectKBest
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error, accuracy_score
from sklearn import datasets, model_selection, metrics

from sklearn.preprocessing import StandardScaler
from sklearn import metrics
from sklearn.model_selection import GridSearchCV

X = final_df[['WBC_Count','Neutrophil_Percentage','Paedriatic_Appendicitis_Score']]

from sklearn.cluster import KMeans

# Num of clusters

model1 = KMeans(n_clusters = 2)

scaler = StandardScaler()
x_scaled = scaler.fit_transform(X)
clusters = model1.fit_predict(x_scaled)

print(clusters)

# 2. Perform PCA
# Reduces dimensions of dataset to just 2 despite having multiple features
pca = PCA()
principal_components = pca.fit_transform(x_scaled)

print("Covariance Matrix:\n", pca.get_covariance(), '\n')
print('\nEigenvalues:', pca.explained_variance_)

pca.components_ # each row is a principal component and each weights applied to each feature

#'WBC_Count','Neutrophil_Percentage','Paedriatic_Appendicitis_Score'

import seaborn as sns

pc_1 = principal_components[:, 0]
pc_2 = principal_components[:, 1]

sns.scatterplot(x = pc_1, y = pc_2, hue = clusters, palette = 'tab10')


plt.title('PCA of Appendicitis Features')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.show()

from sklearn.metrics import silhouette_score

score = silhouette_score(X, model1.labels_, metric='euclidean')
print(score)

print("Explained Variance Ratios:", pca.explained_variance_ratio_, '\n')


total_explained_variances = []
for i in range(len(pca.explained_variance_ratio_)):
  total_explained_variances.append(sum(pca.explained_variance_ratio_[:i + 1]))
  print('Total explained variance including', i + 1, 'components:', total_explained_variances[-1])
  print('We', 'should use more components' if total_explained_variances[-1] < 0.9 else 'do not need to use more components.', '\n')

metrics.ConfusionMatrixDisplay()

"""# Convolutional Neural Network Grad-CAM

"""

# Import Libraries
!pip install --quiet gdown==4.5.4 --no-cache-dir
!pip install torchsummary
from torchsummary import summary

import os
import random

import numpy as np
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
from fastai.vision.all import *

from torch.utils.data import DataLoader
import matplotlib.pyplot as plt
import torchvision
from torchvision import datasets, transforms
from torchvision.datasets import ImageFolder

from fastai.optimizer import Adam


device = torch.device("cuda" if torch.cuda.is_available() else "cpu") # PyTorch v0.4.0

model2 = nn.Sequential(

    #Block 1
    nn.Conv2d(3,16,  kernel_size = 3, padding = 1),
    nn.ReLU(),
    nn.MaxPool2d(2,2),

    #Block 2
    nn.Conv2d(16,32,  kernel_size = 3, padding = 1),
    nn.ReLU(),
    nn.MaxPool2d(2,2),

    #Block 3
    nn.Conv2d(32,64,  kernel_size = 3, padding = 1),
    nn.ReLU(),
    nn.MaxPool2d(2,2),

    #Block 4
    nn.Conv2d(64,128,  kernel_size = 3, padding = 1),
    nn.ReLU(),
    nn.MaxPool2d(2,2),

    #Block 5
    nn.Conv2d(128,256,  kernel_size = 3, padding = 1),
    nn.ReLU(),
    nn.MaxPool2d(2,2),

    #Flatten
    nn.Flatten(),

    #Neural Network
    # nn.Linear(145*200*32,128),
    nn.Linear(115200,128),
    nn.Linear(128,1)

)

#model2.add_module('layer4',nn.Conv2d(128,256,  kernel_size = 3, padding = 1))
#model2.add_module('ReLU',nn.ReLU())
#model2.add_module('Pooling',nn.MaxPool2d(2,2))
#model2.add_module('Flatten',Flatten())
#model2.add_module('linear1',nn.Linear(115200,128))
#model2.add_module('linear2',nn.Linear(128,1))

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision.models import resnet18, ResNet18_Weights
from torchvision.datasets import ImageFolder
from torchvision import transforms
from torch.utils.data import DataLoader
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from tqdm import tqdm
from pathlib import Path
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

loss_function = nn.BCEWithLogitsLoss()
optimizer = optim.SGD(model2.parameters(), lr = 1e-4, momentum = 0.9)

# loop over each epoch
num_epochs = 20
for epoch in range(num_epochs):
    model2.train()
    running_loss = 0.0
    for image, label in tqdm(train_loader):
      optimizer.zero_grad()
      outputs = model2(image)
      loss = loss_function(outputs, label.unsqueeze(dim = -1).float())
      # print(outputs)
      #print(label.unsqueeze(dim = -1).float())
      # print(outputs.shape)
      #print(label.unsqueeze(dim = -1).float().shape)
      #print(loss)
      # break
      loss.backward()
      optimizer.step()
      running_loss += loss.item()
    print(f"Epoch {epoch+1}/{num_epochs}, Loss: {running_loss/len(train_loader):.4f}")

torch.save(model2, "EfficientNetModel.pth")
model2 = torch.load("/content/EfficientNetModel.pth", weights_only = False)

model2.eval()
correct = 0
total = 0

with torch.no_grad():
    for image, label in test_loader:
        outputs = model2(image)
        _, prediction = torch.max(outputs, 1)
        total += label.size(0)
        correct += (prediction == label).sum().item()

# Report the percentage classified correctly
accuracy = correct / total
print(f"Validation Accuracy: {accuracy:.2%}")

#Confusion matrix for laboratory values
model2.eval()
all_predictions=[]
all_true_labels=[]

with torch.no_grad():
  for images, labels in test_loader:
    outputs = model2(images)

    predicted_probs = torch.sigmoid(outputs)
    predicted_classes = (predicted_probs >= 0.5).int()

    all_predictions.extend(predicted_classes.squeeze().cpu().numpy())
    all_true_labels.extend(labels.cpu().numpy())

cm = confusion_matrix(all_true_labels, all_predictions)

disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=[0,1])
disp.plot(cmap=plt.cm.Blues)
plt.title("Confusion Matrix for CNN Model")
plt.show()

"""# New Section"""

print(model2)
print(len(model2))

"""# Grad CAM

"""

!pip install grad-cam -q
from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.model_targets import ClassifierOutputTarget
from pytorch_grad_cam.utils.image import show_cam_on_image
from torchvision import transforms

import torch
import torch.nn as nn
from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.model_targets import ClassifierOutputTarget
from pytorch_grad_cam.utils.image import show_cam_on_image
from torchvision import transforms
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

# Define a wrapper class for model2 to explicitly handle flattening
class GradCamModel(nn.Module):
    def __init__(self, original_model):
        super(GradCamModel, self).__init__()
        # Separate the convolutional layers (features) from the linear layers (classifier)
        # model2 layers (0-14) are features, (16-17) are classifier layers with Flatten (15) in between
        self.features = nn.Sequential(*original_model[:15]) # Layers up to (and including) the last MaxPool2d
        self.classifier_start = original_model[16] # The first Linear layer
        self.classifier_end = original_model[17]   # The second Linear layer

    def forward(self, x):
        x = self.features(x)
        x = x.flatten(1) # Manually flatten the tensor after features
        x = self.classifier_start(x)
        x = self.classifier_end(x)
        return x

# Instantiate the GradCamModel with the existing trained model2
model_for_cam = GradCamModel(model2)
model_for_cam.eval() # Set the model to evaluation mode

# Define the target layer for Grad-CAM
# This should be the last convolutional layer. In the original model2, this was layer 12.
# In GradCamModel, this corresponds to model_for_cam.features[12] if features = nn.Sequential(*original_model[:15])
target_layer = model_for_cam.features[12] # This is nn.Conv2d(128, 256, ...)

# Use a specific image path for consistent demonstration
image_path = '/content/US_Pictures/102.4 App.bmp' # Path to a sample image
original_image_pil = Image.open(image_path).convert('RGB')

# Prepare the input tensor using the defined transform (`my_transform` from earlier cells)
input_tensor = my_transform(original_image_pil).unsqueeze(0) # Add batch dimension

# Create GradCAM object
cam = GradCAM(model=model2, target_layers=[target_layer])

# Define targets (e.g., class index 1 for the positive class in binary classification)
# Assuming the model outputs raw logits which are then interpreted for class 1
targets = [ClassifierOutputTarget(0)] # Changed from 1 to 0

# Generate grayscale Grad-CAM heatmap
grayscale_cam = cam(input_tensor=input_tensor, targets=targets)
grayscale_cam = grayscale_cam[0, :] # Remove batch dimension for visualization

# Prepare original image for visualization (scale to 0-1 and resize if needed)
# The `my_transform` resizes to (580, 800), so we use those dimensions for display consistency
original_image_np = np.array(original_image_pil.resize((800, 580))) / 255.0 # Resize PIL image to match input_tensor dimensions and scale

# Visualize the heatmap
plt.figure(figsize=(10, 7))
plt.imshow(original_image_np)
plt.imshow(grayscale_cam, cmap='jet', alpha=0.5) # Overlay heatmap
plt.title(f"Grad-CAM for image {image_path.split('/')[-1]}")
plt.axis('off')
plt.savefig("figure_1.png")
plt.show()

model2.eval
target_layer = model2[12]
image_path = '/content/US_Pictures/102.4 App.bmp'
original_image = np.array(image.resize((224, 224))) / 255
input_tensor = my_transform(image)
cam = GradCAM(model = model2, target_layers = [target_layer])
targets = [ClassifierOutputTarget(1)]

grayscale_cam = cam(input_tensor = input_tensor, targets = targets)

sample_path = '/content/US_Pictures/102.4 App.bmp'
image = Image.open(sample_path)
input_tensor = my_transform(image).unsqueeze(0)
original_image = np.array(image.resize((224, 224))) / 255
model2.eval()
with torch.no_grad():
  output = model2(input_tensor)
  print(output)




# this is just to display the prepared image
plt.imshow(original_image)
plt.title("Original Image (prepared)")
plt.axis('off')
plt.show()
print(input_tensor.shape)

print(output)

print(torch.max(output,1))

predicted_class = 1

with GradCAM(model=model2, target_layers=target_layers) as cam:
    grayscale_cam = cam(input_tensor=input_tensor, targets=[ClassifierOutputTarget(predicted_class)])
    print(grayscale_cam)

# display for reference
plt.imshow(grayscale_cam[0], cmap='jet')
plt.title("Raw Heatmap")
plt.axis('off')
plt.show()







"""# Visualizing Relationships"""

# Correlation between WBC and Hemoglobin
plt.scatter(patient_df['WBC_Count'],patient_df['Paedriatic_Appendicitis_Score'])

plt.title('WBC and Paedriatic_Appendicitis_Score Correlation')
plt.xlabel('White Blood Cell')
plt.ylabel('Paedriatic_Appendicitis_Score')
plt.show()

#plt.bar(patient_df["Appendix_on_US"], patient_df["Paedriatic_Appendicitis_Score"])

#plt.title('Appendix_on_US and Paedriatic_Appendicitis_Score ')
#plt.ylabel('Paedriatic_Appendicitis_Score')
#plt.xlabel('Appendix_on_US')
#plt.show()

plt.scatter(patient_df["Alvarado_Score"], patient_df["Paedriatic_Appendicitis_Score"])

plt.title('Paedriatic_Appendicitis_Score  and Alvarado_Score')
plt.ylabel('Paedriatic_Appendicitis_Score ')
plt.xlabel('Alvarado_Score')
plt.show()